version: '3.8'

services:
  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.11.3
    networks:
      - selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/vladislav/selenoid/browsers.json:/etc/selenoid/browsers.json:ro
    command:
      - "-container-network=selenoid"
      - "-limit=12"
  ggr:
    container_name: ggr
    depends_on:
      - selenoid
    image: aerokube/ggr:1.7.2
    networks:
      - selenoid
    volumes:
      - /home/vladislav/selenoid/grid:/etc/grid-router:ro
    command:
      - "-guests-allowed"
      - "-guests-quota=test"
      - "-verbose"
      - "-quotaDir=/etc/grid-router/quota"
  ggr-ui:
    container_name: ggr-ui
    depends_on:
      - ggr
    image: aerokube/ggr-ui:1.2.0
    networks:
      - selenoid
    volumes:
      - /home/vladislav/selenoid/grid/quota:/etc/grid-router/quota:ro
  selenoid-ui:
    container_name: selenoid-ui
    depends_on:
      - ggr-ui
    image: aerokube/selenoid-ui:1.10.11
    networks:
      - selenoid
    command: 
      - "--selenoid-uri"
      - "http://ggr-ui:8888"
  nginx:
    container_name: nginx
    depends_on:
      - selenoid-ui
    image: nginx:1.27.0
    networks:
      - selenoid
    ports:
      - "80:80"
    volumes:
      - /home/vladislav/nginx/:/etc/nginx/conf.d:ro
networks:
  selenoid:
    name: selenoid
    external: true
